# Generated by Django 3.2.7 on 2021-09-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('published_at', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='tech_crunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('published_at', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
