# Generated by Django 3.2.7 on 2021-09-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210917_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_crunch',
            name='author',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tech_crunch',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tech_crunch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tech_crunch',
            name='published_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tech_crunch',
            name='source_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tech_crunch',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tech_crunch',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
