# Generated by Django 3.2.7 on 2021-09-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210917_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tech_crunch',
        ),
    ]
