# Generated by Django 3.2.7 on 2021-09-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_delete_tech_crunch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_model',
            options={'ordering': ('-title',)},
        ),
    ]
