# Generated by Django 3.2.7 on 2021-09-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_news_model_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_model',
            options={},
        ),
    ]
