# Generated by Django 3.2.7 on 2021-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_news_model_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='source_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='source_select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_source', models.ManyToManyField(to='application.source_name')),
            ],
        ),
    ]
