# Generated by Django 3.2.7 on 2021-09-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_source_name_source_select'),
    ]

    operations = [
        migrations.DeleteModel(
            name='source_select',
        ),
    ]
