# Generated by Django 3.2.7 on 2021-10-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_source_select'),
    ]

    operations = [
        migrations.DeleteModel(
            name='source_select',
        ),
    ]
