# Generated by Django 3.2.7 on 2021-10-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_delete_source_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='source_select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.ManyToManyField(to='application.source_name')),
            ],
        ),
    ]
